# Google App Engine configuration for Journai Travel App
runtime: nodejs18

# Service configuration
service: default

# Environment variables
env_variables:
  NODE_ENV: production
  VITE_ADMIN_ENABLED: false
  VITE_ADMIN_DEBUG: false

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 20
  min_idle_instances: 1
  max_idle_instances: 3
  min_pending_latency: 30ms
  max_pending_latency: automatic
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource allocation
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Network settings
network:
  forwarded_ports:
    - 8080
  instance_tag: journai-app

# Health check configuration
readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2
  initial_delay_sec: 30

# Static file handling
handlers:
- url: /favicon.ico
  static_files: dist/favicon.ico
  upload: dist/favicon.ico
  secure: always

- url: /assets
  static_dir: dist/assets
  secure: always
  expiration: 1d
  http_headers:
    Cache-Control: "public, max-age=86400"

- url: /static
  static_dir: dist/static
  secure: always
  expiration: 1d

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html