# Google Cloud Build configuration for Journai Travel App
steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']

  # Setup database (if needed)
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'setup:database']
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'SUPABASE_PROJECT_ID=$_SUPABASE_PROJECT_ID'

  # Build the application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'VITE_SUPABASE_URL=$_SUPABASE_URL'
      - 'VITE_SUPABASE_ANON_KEY=$_SUPABASE_ANON_KEY'
      - 'VITE_ADMIN_ENABLED=false'

  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']

# Substitution variables (set these in Cloud Build triggers)
substitutions:
  _SUPABASE_PROJECT_ID: 'your-supabase-project-id'
  _SUPABASE_URL: 'https://your-project.supabase.co'
  _SUPABASE_ANON_KEY: 'your-supabase-anon-key'

# Build timeout
timeout: '1200s'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'